### ISSUE TITLE
Can add device to WebThings Gateway

### ISSUE THREAD

**Issue by PPCM** [tim-hellhake/tasmota-adapter#4] opened 2019-12-15 23:40 UTC
I am not able to see the Tasmota device in WebThings Gateway, even after adding to the console of Tasmota the command "SetOption55 ON".

Any idea to see the device when adding in the gateway?

**Comment by tim-hellhake** [comment] 2019-12-15 23:45
Could you please attach the logs.
That would help me to understand what is happening.

**Comment by PPCM** [comment] 2019-12-16 00:04
Thanks for the quick answer.

In Tasmota device, here are informations:
```
Program Version | 7.1.2(tasmota)
-- | --
2019-12-06T11:22:22
2_6_1/2.2.2-dev(38a443e)
0T00:32:38
35 at 0xF9000
16
Software/System restart
Prise-Test2
 
WIFI_SSID(76%)
tasmota-6492.local
xxx.xxx.xxx.xxx
xxx.xxx.xxx.xxx
255.255.255.0
xxx.xxx.xxx.xxx
yy:yy:yy:yy
 
 
1883
DVES_USER
DVES_5B795C
tasmota
cmnd/tasmotas/
cmnd/tasmota/
cmnd/DVES_5B795C_fb/
 
None
Enabled
Web Server
 
5994844
0x144068
1024kB
1024kB
562kB
440kB
26kB
```

In Webthings Gateway, the only log for tasmota-adapter is
```
2019-12-16 01:00:36.172 INFO   : tasmota: Adapter: TasmotaAdapter id Tasmota pairing started
```

**Comment by tim-hellhake** [comment] 2019-12-16 00:38
Strange, there should be more logs.
Please restart the adapter and look for log messages which begin with _Discovered http service at_.
For tasmota devices they should be followed by messages which begin with _Discovered device at_.

**Comment by PPCM** [comment] 2019-12-16 00:41
When you talk about adapter are you talking about the Tasmota device or the Webthings Gateway?

**Comment by PPCM** [comment] 2019-12-16 00:53
Here are start logs of the Tasmota device:

```
00:00:00 CFG: Loaded from flash at F4, Count 40
00:00:00 Project tasmota Prise-Test2 Version 7.1.2(tasmota)-2_6_1
00:00:00 WIF: Connecting to AP1 PinpinLand in mode 11N as tasmota-6492...
00:00:06 WIF: Connected
00:00:06 DNS: Initialized
00:00:06 HTP: Web server active on tasmota-6492.local with IP address xxx.xxx.xxx.xxx
00:00:06 RSL: INFO1 = {"Module":"ZooZee SE131","Version":"7.1.2(tasmota)","FallbackTopic":"cmnd/DVES_5B795C_fb/","GroupTopic":"cmnd/tasmotas/"}
00:00:06 RSL: INFO2 = {"WebServerMode":"Admin","Hostname":"tasmota-6492","IPAddress":"xxx.xxx.xxx.xxx"}
00:00:06 RSL: INFO3 = {"RestartReason":"Software/System restart"}
00:00:06 RSL: RESULT = {"POWER":"OFF"}
00:00:06 RSL: POWER = OFF
01:50:54 RSL: STATE = {"Time":"2019-12-16T01:50:54","Uptime":"0T00:00:12","UptimeSec":12,"Heap":28,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER":"OFF","Wifi":{"AP":1,"SSId":"My_SSID","BSSId":"10:7B:44:AE:B6:50","Channel":3,"RSSI":62,"LinkCount":1,"Downtime":"0T00:00:07"}}
```

if it can help...

**Comment by tim-hellhake** [comment] 2019-12-16 01:00
Sorry for the confusion.
With _adapter_ i meant the tasmota adapter.
You can disable and enable it in the _add-ons_ section of the gateway.

Btw. do you already have a MQTT server running for tasmota?

**Comment by PPCM** [comment] 2019-12-16 01:45
I never had a MQTT server on this network.

When I disable/enable the tasmota add-on, it is more verbose:
```
Dec 16 02:31:14 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-16 02:31:14.980 INFO   : Loading add-on: tasmota-adapter#033[22m#033[39m
Dec 16 02:31:15 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-16 02:31:15.879 INFO   : tasmota: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3#033[22m#033[39m
Dec 16 02:31:16 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-16 02:31:16.557 INFO   : tasmota: Loading add-on tasmota-adapter from /home/pi/.mozilla-iot/addons/tasmota-adapter#033[22m#033[39m
Dec 16 02:31:16 XXXXXX run-app.sh[556]: #033[31m2019-12-16 02:31:16.810 ERROR  : Invalid message received: { messageType: 4096,#033[39m
Dec 16 02:31:16 XXXXXX run-app.sh[556]: #033[31m  data: #033[39m
Dec 16 02:31:16 XXXXXX run-app.sh[556]: #033[31m   { adapterId: 'Tasmota',#033[39m
Dec 16 02:31:16 XXXXXX run-app.sh[556]: #033[31m     name: 'TasmotaAdapter',#033[39m
Dec 16 02:31:16 XXXXXX run-app.sh[556]: #033[31m     pluginId: 'tasmota-adapter' } }#033[39m
Dec 16 02:31:16 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-16 02:31:16.910 INFO   : tasmota: Discovered http service at YYYYYYYYYY.local:8080#033[22m#033[39m
Dec 16 02:31:19 pinpinland run-app.sh[556]: #033[37m#033[2m2019-12-16 02:31:19.339 INFO   : tasmota: Discovered http service at tasmota-6492.local:80#033[22m#033[39m
```
The last discovered device is the Tasmota Adapter

And when I try to add a component, here is the logs:
```
Dec 16 02:37:27 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-16 02:37:27.419 INFO   : Opened a new things socket#033[22m#033[39m
Dec 16 02:37:27 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-16 02:37:27.439 INFO   : About to call startPairing on DateTimeAdapter#033[22m#033[39m
Dec 16 02:37:27 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-16 02:37:27.440 INFO   : About to call startPairing on SpeedTestAdapter#033[22m#033[39m
Dec 16 02:37:27 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-16 02:37:27.442 INFO   : About to call startPairing on HttpAdapter#033[22m#033[39m
Dec 16 02:37:27 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-16 02:37:27.444 INFO   : About to call startPairing on TasmotaAdapter#033[22m#033[39m
Dec 16 02:37:27 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-16 02:37:27.448 INFO   : About to call startPairing on ThingURLAdapter#033[22m#033[39m
Dec 16 02:37:27 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-16 02:37:27.464 INFO   : speed-test: AddonManagerProxy: recv: b'{"messageType":4099,"data":{"timeout":60,"adapterId":"speed-test-adapter","pluginId":"speed-test-adapter"}}'#033[22m#033[39m
Dec 16 02:37:27 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-16 02:37:27.468 INFO   : http: Adapter: HttpAdapter id HttpAdapter pairing started#033[22m#033[39m
Dec 16 02:37:27 pinpinland run-app.sh[556]: #033[37m#033[2m2019-12-16 02:37:27.472 INFO   : tasmota: Adapter: TasmotaAdapter id Tasmota pairing started#033[22m#033[39m
```

And at the end, no Tasmota adapter to add at the list of devices

**Comment by tim-hellhake** [comment] 2019-12-16 23:28
> tasmota: Discovered http service at tasmota-6492.local:80

I looks like the adapter saw the device but did not recognize it as tasmota device.

A new version of the adapter is available.
Please try to add the things again after the update and attach the new logs.

**Comment by PPCM** [comment] 2019-12-17 07:14
In fact, the add-on doesn't see the Tasmota adapter, it see other devices and for one of them, the add-on do a bad guess:

```
Dec 17 08:00:00 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-17 08:00:00.456 INFO   : About to call startPairing on TasmotaAdapter#033[22m#033[39m
Dec 17 08:00:00 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-17 08:00:00.490 INFO   : tasmota: Start pairing#033[22m#033[39m
Dec 17 08:00:00 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-17 08:00:00.654 INFO   : tasmota: Discovered http service at octopi.local#033[22m#033[39m
Dec 17 08:00:00 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-17 08:00:00.655 INFO   : tasmota: Probing xxx.xxx.xxx.xxx:80#033[22m#033[39m
Dec 17 08:00:00 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-17 08:00:00.679 INFO   : tasmota: Discovered http service at PinPinNASQ01.local#033[22m#033[39m
Dec 17 08:00:00 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-17 08:00:00.680 INFO   : tasmota: Probing yyy.yyy.yyy.yyy:8080#033[22m#033[39m
Dec 17 08:00:00 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-17 08:00:00.688 INFO   : tasmota: PinPinNASQ01.local seems not to be a Tasmota device#033[22m#033[39m
Dec 17 08:00:01 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-17 08:00:01.491 INFO   : tasmota: octopi.local seems not to be a Tasmota device#033[22m#033[39m
Dec 17 08:01:00 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-17 08:01:00.468 INFO   : Pairing timeout#033[22m#033[39m
Dec 17 08:01:00 XXXXXX run-app.sh[556]: #033[37m#033[2m2019-12-17 08:01:00.495 INFO   : tasmota: Cancel pairing#033[22m#033[39m
```

The name of the Tasmota adapter is `tasmota-6492`

Logs on the console of the Tasmota adapter:
```
00:00:00 CFG: Loaded from flash at FA, Count 49
00:00:00 Project tasmota Prise-Test2 Version 7.1.2(tasmota)-2_6_1
00:00:00 WIF: Connecting to AP1 PinpinLand in mode 11N as tasmota-6492...
00:00:05 WIF: Connected
00:00:05 DNS: Initialized
00:00:05 HTP: Web server active on tasmota-6492.local with IP address xxx.xxx.xxx.xxx
00:00:05 RSL: INFO1 = {"Module":"ZooZee SE131","Version":"7.1.2(tasmota)","FallbackTopic":"cmnd/DVES_5B795C_fb/","GroupTopic":"cmnd/tasmotas/"}
00:00:05 RSL: INFO2 = {"WebServerMode":"Admin","Hostname":"tasmota-6492","IPAddress":"xxx.xxx.xxx.xxx"}
00:00:05 RSL: INFO3 = {"RestartReason":"Software/System restart"}
00:00:05 RSL: RESULT = {"POWER":"OFF"}
00:00:05 RSL: POWER = OFF
07:55:19 RSL: STATE = {"Time":"2019-12-17T07:55:19","Uptime":"0T00:00:11","UptimeSec":11,"Heap":28,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":24,"MqttCount":0,"POWER":"OFF","Wifi":{"AP":1,"SSId":"PinpinLand","BSSId":"10:7B:44:AE:B6:50","Channel":13,"RSSI":76,"LinkCount":1,"Downtime":"0T00:00:06"}}
08:00:19 RSL: STATE = {"Time":"2019-12-17T08:00:19","Uptime":"0T00:05:11","UptimeSec":311,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER":"OFF","Wifi":{"AP":1,"SSId":"PinpinLand","BSSId":"10:7B:44:AE:B6:50","Channel":13,"RSSI":76,"LinkCount":1,"Downtime":"0T00:00:06"}}
08:05:08 APP: Serial logging disabled
08:05:19 RSL: STATE = {"Time":"2019-12-17T08:05:19","Uptime":"0T00:10:11","UptimeSec":611,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER":"OFF","Wifi":{"AP":1,"SSId":"MySSID","BSSId":"10:7B:44:AE:B6:50","Channel":13,"RSSI":78,"LinkCount":1,"Downtime":"0T00:00:06"}}
```

Versions of different elements:
Mozilla WebThings Gateway : 0.10.0
Tasmota add-on : 0.1.1
Tasmota adapter : 7.1.2

**Comment by tim-hellhake** [comment] 2019-12-21 19:41
> In fact, the add-on doesn't see the Tasmota adapter

Strange, it already worked [here](https://github.com/tim-hellhake/tasmota-adapter/issues/4#issuecomment-565873223).
Did you change anything since then?

> it see other devices and for one of them, the add-on do a bad guess

Which one do you mean?
As far as I can see, the adapter found `PinPinNASQ01` and `octopi` and considered both not to be a Tasmota device.

On which device is the Tasmota firmware running?

**Comment by PPCM** [comment] 2019-12-23 01:33
> Strange, it already worked [here](https://github.com/tim-hellhake/tasmota-adapter/issues/4#issuecomment-565873223).
> Did you change anything since then?

Nothing change on my side

> Which one do you mean?
> As far as I can see, the adapter found `PinPinNASQ01` and `octopi` and considered both not to be a Tasmota device.

You are right, I made a mistake, sorry. Other founded devices are well rejected

> On which device is the Tasmota firmware running?

The name of the Tasmota device is `tasmota-6492` and the adapter doesn't see it
But previously, it was seen (previous version of the adapter???)

I confirm, the adapter see some of my network devices, not all of them, for exemple my router is not seen
The Google Home is not seen too, but it is already added to the Gateway, perhaps it has an impact in the discovering process

I can send you the dump of the configuration of Tasmota device, perhaps I made a mistake somewhere...

The firmware of the Tasmota device was updated today to 7.2.0

**Comment by PPCM** [comment] 2019-12-23 01:44
After lot of tries, the adapter can see the Tasmota device, here are logs of the Gateway
```
Dec 23 02:39:08 XXXXXX run-app.sh[561]: #033[37m#033[2m2019-12-23 02:39:08.546 INFO   : tasmota: Discovered http service at tasmota-6492.local#033[22m#033[39m
Dec 23 02:39:08 XXXXXX run-app.sh[561]: #033[37m#033[2m2019-12-23 02:39:08.546 INFO   : tasmota: Probing 192.168.0.106:80#033[22m#033[39m
Dec 23 02:39:08 XXXXXX run-app.sh[561]: #033[37m#033[2m2019-12-23 02:39:08.626 INFO   : tasmota: tasmota-6492.local responded with 401#033[22m#033[39m
Dec 23 02:39:59 XXXXXX run-app.sh[561]: #033[37m#033[2m2019-12-23 02:39:59.965 INFO   : tasmota: Cancel pairing#033[22m#033[39m
```

To have this, I rebooted the Raspberry PI, to see if something changes

So now, the Tasmota device is seen by the adapter (cf logs), but nothing on the gateway interface

**Comment by tim-hellhake** [comment] 2019-12-23 22:02
```
Dec 23 02:39:08 XXXXXX run-app.sh[561]: #033[37m#033[2m2019-12-23 02:39:08.626 INFO   : tasmota: tasmota-6492.local responded with 401#033[22m#033[39m
```

There it is.
The tasmota device is rejected because of the missing authorization.
I'll add user and password fields to the settings.

**Comment by PPCM** [comment] 2019-12-24 13:59
Great, things evolve!!!

The adapter updated to 0.2.1

I don't have fields for user and password to the settings (the gateway was restarted to be sure), but now on logs I have:

```
Dec 24 14:53:14 XXXXXX run-app.sh[527]: #033[37m#033[2m2019-12-24 14:53:14.762 INFO   : tasmota: Probing 192.168.0.106:80#033[22m#033[39m
Dec 24 14:53:17 XXXXXX run-app.sh[527]: #033[37m#033[2m2019-12-24 14:53:17.872 INFO   : tasmota: Unhandled Rejection#033[22m#033[39m
Dec 24 14:53:17 XXXXXX run-app.sh[527]: #033[31m2019-12-24 14:53:17.875 ERROR  : tasmota: { FetchError: request to http://192.168.0.106:80/ failed, reason: connect EHOSTUNREACH 192.168.0.106:80#033[39m
Dec 24 14:53:17 XXXXXX run-app.sh[527]: #033[31m2019-12-24 14:53:17.876 ERROR  : tasmota:     at ClientRequest.<anonymous> (/home/pi/.mozilla-iot/addons/tasmota-adapter/node_modules/node-fetch/lib/index.js:1455:11)#033[39m
Dec 24 14:53:17 XXXXXX run-app.sh[527]: #033[31m2019-12-24 14:53:17.877 ERROR  : tasmota:     at emitOne (events.js:116:13)#033[39m
Dec 24 14:53:17 XXXXXX run-app.sh[527]: #033[31m2019-12-24 14:53:17.878 ERROR  : tasmota:     at ClientRequest.emit (events.js:211:7)#033[39m
Dec 24 14:53:17 XXXXXX run-app.sh[527]: #033[31m2019-12-24 14:53:17.879 ERROR  : tasmota:     at Socket.socketErrorListener (_http_client.js:401:9)#033[39m
Dec 24 14:53:17 XXXXXX run-app.sh[527]: #033[31m2019-12-24 14:53:17.880 ERROR  : tasmota:     at emitOne (events.js:116:13)#033[39m
Dec 24 14:53:17 XXXXXX run-app.sh[527]: #033[31m2019-12-24 14:53:17.881 ERROR  : tasmota:     at Socket.emit (events.js:211:7)#033[39m
Dec 24 14:53:17 XXXXXX run-app.sh[527]: #033[31m2019-12-24 14:53:17.882 ERROR  : tasmota:     at emitErrorNT (internal/streams/destroy.js:73:8)#033[39m
Dec 24 14:53:17 XXXXXX run-app.sh[527]: #033[31m2019-12-24 14:53:17.883 ERROR  : tasmota:     at _combinedTickCallback (internal/process/next_tick.js:139:11)#033[39m
Dec 24 14:53:17 XXXXXX run-app.sh[527]: #033[31m2019-12-24 14:53:17.884 ERROR  : tasmota:     at process._tickCallback (internal/process/next_tick.js:181:9)#033[39m
Dec 24 14:53:17 XXXXXX run-app.sh[527]: #033[31m2019-12-24 14:53:17.884 ERROR  : tasmota:   message: 'request to http://192.168.0.106:80/ failed, reason: connect EHOSTUNREACH 192.168.0.106:80',#033[39m
Dec 24 14:53:17 XXXXXX run-app.sh[527]: #033[31m2019-12-24 14:53:17.885 ERROR  : tasmota:   type: 'system',#033[39m
Dec 24 14:53:17 XXXXXX run-app.sh[527]: #033[31m2019-12-24 14:53:17.886 ERROR  : tasmota:   errno: 'EHOSTUNREACH',#033[39m
Dec 24 14:53:17 XXXXXX run-app.sh[527]: #033[31m2019-12-24 14:53:17.887 ERROR  : tasmota:   code: 'EHOSTUNREACH' }#033[39m
Dec 24 14:53:49 XXXXXX run-app.sh[527]: #033[37m#033[2m2019-12-24 14:53:49.673 INFO   : Pairing timeout#033[22m#033[39m
Dec 24 14:53:49 XXXXXX run-app.sh[527]: #033[31m2019-12-24 14:53:49.677 ERROR  : Thing was not added#033[39m
Dec 24 14:53:49 XXXXXX run-app.sh[527]: #033[31m2019-12-24 14:53:49.678 ERROR  : addNewThing cancelled#033[39m
```

**Comment by tim-hellhake** [comment] 2019-12-24 23:57
The last update (0.2.1) was about devices with power metering.
With release 0.3.0 there should be a `password` field in the settings of the addon.

**Comment by tim-hellhake** [comment] 2019-12-24 23:58
The last update (0.2.1) was about devices with power metering.
Release 0.3.0 introduces a password field in the settings of the addon.
This should solve the problem.

**Comment by tim-hellhake** [comment] 2019-12-24 23:59
The last release (0.2.1) was about devices with power metering.
Release 0.3.0 introduces a password field in the settings of the addon.
This should solve the problem.

**Comment by PPCM** [comment] 2019-12-25 12:00
Much much much better
It takes a long time to discover the Tasmota device, but now it works fine
Thanks a lot...

**Comment by tim-hellhake** [comment] 2019-12-26 16:01
> It takes a long time to discover the Tasmota device

I can confirm that the discovery takes some time after restarting the tasmota device.
This also happens on config changes.
According to wireshark the device needs a few minutes before it responds to mDNS queries.
When it starts working, the discovery is really fast though.
I the problem persists this may be related to your network setup.
Would it help you if you could add the devices manually?

**Comment by PPCM** [comment] 2020-01-06 14:27
In fact, I notice that if the gateway doesn't ping tasmota device when it starts, it still stays disconnected
When I restart the gateway server (Raspberry Pi) it takes a very long time before the server can ping again tasmota devices

It will be great if the add-on tries periodically if Tasmota devices are still connected or disconnected
For me, if I restart the gateway, I have to remove then add again all tasmota devices

**Comment by Catalin84** [comment] 2020-01-20 05:28
> I am not able to see the Tasmota device in WebThings Gateway, even after adding to the console of Tasmota the command "SetOption55 ON".
> 
> Any idea to see the device when adding in the gateway?

Try to restart the Tasmota device.

**Comment by off-my-lawn** [comment] 2020-02-18 07:12
In my case I had problems with this because tasmota did not enable mDNS when calling SetOption55 1. This could be verified on the Information page which listed mDNS as disabled. I had to reflash my device to make it work.

**Comment by tim-hellhake** [comment] 2020-02-20 23:38
@PPCM 
I added the option to add devices manually: https://github.com/tim-hellhake/tasmota-adapter/issues/15.
There is also an issue for speeding up device discovery at start-up by remembering them: https://github.com/tim-hellhake/tasmota-adapter/issues/9.
I'm closing this now as the original problem is solved.

**Closed as completed by tim-hellhake** 2020-02-20 23:38 UTC
